{{- range $_, $https := .Values.app.ingress.https }}
{{- if eq $https.managedBy "cert-manager" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $https.secretName | quote }}
  namespace: istio-system
  labels:
    {{ $.Values.app.group }}/app-name: {{ $.Values.app.name | quote }}
spec:
  secretName: {{ $https.secretName }}
  dnsNames:
    - {{ $https.cname }}
  issuerRef:
    name: {{ $.Values.ingressController.clusterIssuer }}
    kind: ClusterIssuer
---
{{ end }}
{{ end }}
