{{- range $_ , $deployment := .Values.app.deployments }}
  {{- range $_, $process := $deployment.processes }}
  {{- if $process.routable }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: shipa-{{ empty $.Values.app.id | ternary $.Values.app.name (printf "%s-%s" $.Values.app.name $.Values.app.id) }}-rule-{{ $deployment.version }}
  labels:
    {{- if $.Values.app.id }}
    {{ $.Values.app.group }}/app-id: {{ $.Values.app.id | quote }}
    {{- end }}
    {{ $.Values.app.group }}/app-name: {{ $.Values.app.name | quote }}
    {{ $.Values.app.group }}/app-deployment-version: {{ $deployment.version | quote }}
spec:
  host: {{ empty $.Values.app.id | ternary $.Values.app.name (printf "%s-%s" $.Values.app.name $.Values.app.id) }}-{{ $process.name }}-{{ $deployment.version }}
  subsets:
    - name: v{{ $deployment.version }}
      labels:
        app: {{ default $.Values.app.name $.Values.app.id | quote }}
        version: "{{ $deployment.version }}"
---
  {{- end }}
  {{- end }}
{{- end }}