{{- if .Values.app.isAccessible }}
{{- if or .Values.app.ingress.http .Values.app.ingress.https }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  labels:
    {{ $.Values.app.group }}/app-name: {{ $.Values.app.name | quote }}
  name: {{ $.Values.app.name }}-http-gateway
  {{- $data := dict "kind" "Gateway" "apiVersion" "networking.istio.io/v1alpha3" "metadataItems" $.Values.app.metadataAnnotations }}
  annotations: {{- include "ketch.renderMetadata" $data | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
    {{- range $_, $deployment := $.Values.app.deployments }}
      {{- range $_, $process := $deployment.processes }}
      {{- if $process.routable }}
       {{- if  $.Values.app.ingress.http }}
  - port:
      number: 80
      name: http-{{ $deployment.version }}
      protocol: HTTP
    hosts:
      {{- range $_, $cname := $.Values.app.ingress.http }}
    - {{ $cname }}
      {{- end }}
        {{- end }}
    {{- if  $.Values.app.ingress.https }}
    {{- range $_, $https := $.Values.app.ingress.https }}
  - port:
      number: 443
      name: https-{{ $deployment.version }}-{{ $https.cname }}
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ $https.secretName }}
    hosts:
    - {{ $https.cname }}
  - port:
      name: http-to-https-{{ $deployment.version }}-{{ $https.cname }}
      number: 80
      protocol: HTTP
    hosts:
    - {{ $https.cname }}
    tls:
      httpsRedirect: true
        {{- end }}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
