{{- if .Values.app.isAccessible }}
{{- if or .Values.app.ingress.http .Values.app.ingress.https }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    {{- if .Values.ingressController.className }}
    kubernetes.io/ingress.class: {{ .Values.ingressController.className | quote }}
    {{- end }}
  labels:
    {{- if $.Values.app.id }}
    {{ $.Values.app.group }}/app-id: {{ $.Values.app.id | quote }}
    {{- end }}
    {{ $.Values.app.group }}/app-name: {{ $.Values.app.name | quote }}
    {{- with (last $.Values.app.deployments) }}
    {{ $.Values.app.group }}/app-deployment-version: {{ .version | quote }}
    {{- end }}
  name: {{ empty $.Values.app.id | ternary $.Values.app.name (printf "%s-%s" $.Values.app.name $.Values.app.id) }}-http
spec:
    hosts:
    {{- if  $.Values.app.ingress.http }}
    {{- range $_, $cname := .Values.app.ingress.http }}
    - {{ $cname }}
    {{- end }}
    {{- end }}
    {{- if  $.Values.app.ingress.https }}
    {{- range $_, $https := .Values.app.ingress.https }}
    - {{ $https.cname }}
    {{- end }}
    {{- end }}
    gateways:
    - {{ $.Values.app.name }}-http-gateway
    http:
    - route:
      {{- range $_, $deployment := $.Values.app.deployments }}
        {{- range $_, $process := $deployment.processes }}
        {{- if $process.routable }}{{- if gt $deployment.routingSettings.weight 0.0}}
        - destination:
            host: {{empty $.Values.app.id | ternary $.Values.app.name (printf "%s-%s" $.Values.app.name $.Values.app.id)}}-{{ $process.name}}-{{ $deployment.version }}
            port:
              number: {{ $process.publicServicePort }}
            subset: "v{{ $deployment.version }}"
          weight: {{$deployment.routingSettings.weight}}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
    {{- end }}
  {{- end }}
