{{- if .Values.app.isAccessible }}
{{- if or .Values.app.ingress.http .Values.app.ingress.https }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    {{- if .Values.ingressController.className }}
    kubernetes.io/ingress.class: {{ .Values.ingressController.className | quote }}
    {{- end }}
  labels:
    {{ $.Values.app.group }}/app-name: {{ $.Values.app.name | quote }}
    {{- with (last $.Values.app.deployments) }}
    {{ $.Values.app.group }}/app-deployment-version: {{ .version | quote }}
    app.kubernetes.io/version: {{ .version | quote }}
    {{- end }}
    app.kubernetes.io/name: {{ $.Values.app.name | quote }}
    app.kubernetes.io/instance: {{ $.Values.app.name | quote }}
    app.kubernetes.io/managed-by: "LensApps"
  name: {{ $.Values.app.name }}-http
spec:
    hosts:
    {{- if  $.Values.app.ingress.http }}
    {{- range $_, $cname := .Values.app.ingress.http }}
    - {{ $cname }}
    {{- end }}
    {{- end }}
    {{- if  $.Values.app.ingress.https }}
    {{- range $_, $https := .Values.app.ingress.https }}
    - {{ $https.cname }}
    {{- end }}
    {{- end }}
    gateways:
    - {{ $.Values.app.name }}-http-gateway
    http:
    - route:
      {{- range $_, $deployment := $.Values.app.deployments }}
        {{- range $_, $process := $deployment.processes }}
        {{- if $process.routable }}{{- if gt $deployment.routingSettings.weight 0.0}}
        - destination:
            host: {{ printf "%s-%s-%v" $.Values.app.name $process.name $deployment.version }}
            port:
              number: {{ $process.publicServicePort }}
            subset: "v{{ $deployment.version }}"
          weight: {{$deployment.routingSettings.weight}}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
    {{- end }}
  {{- end }}
