{{- if .Values.job }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    {{ $.Values.job.group }}/job-name: {{ $.Values.job.name | quote }}
  name: {{ $.Values.job.name | quote }}
spec:
  {{- if $.Values.job.parallelism }}
  parallelism: {{ $.Values.job.parallelism }}
  {{- end }}
  {{- if $.Values.job.completions }}
  completions: {{ $.Values.job.completions }}
  {{- end }}
  {{- if $.Values.job.backoffLimit }}
  backoffLimit: {{ $.Values.job.backoffLimit }}
  {{- end }}
  {{- if $.Values.job.suspend }}
  suspend: {{ $.Values.job.suspend }}
  {{- end }}
  template:
    spec:
      restartPolicy: {{ $.Values.job.policy.restartPolicy }}
      containers:
        {{ range $_, $container := $.Values.job.containers }}
        - name: {{ $container.name }}
          image: {{ $container.image }}
          command: {{ $container.command | toJson }}
        {{ end }}
  {{ end }}